version: '3.8'

services:
  stock-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./history:/app/history
      - ./log:/app/log
      - ./datas:/app/datas
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - stock-app
    restart: unless-stopped 